Add Gabriel's part to AboutUs
AY2122S1-CS2103T-T17-4/tp pull request #34
Opened 2021-09-28 10:39 UTC by kawaiigabrielneko

Resolves #18

2021-09-28 12:17 UTC, xianlinc requested changes

2021-09-28 12:17 UTC, xianlinc commented on docs/AboutUs.md
> +* Responsibilities: Insurance, Glossary
Minor standardisation issue.  
Can you change the comma (,) to a plus (+) ?
e.g Insurance + Glossary

2021-09-28 12:17 UTC, xianlinc commented on docs/AboutUs.md
> +<img src="https://upload.wikimedia.org/wikipedia/en/b/b1/Portrait_placeholder.png" width="200px">
I think that the CS2103 grader will be checking for your picture upload, so you can't use a url.
Could you upload a png of yourself to the images folder, so the grader can pick it up.
Use this format 'images/githbub_username_in_lower_case.png'

2021-09-28 14:03 UTC, JoelChanZhiYang commented on docs/AboutUs.md
> +<img src="https://upload.wikimedia.org/wikipedia/en/b/b1/Portrait_placeholder.png" width="200px">
I think this is allowed

2021-09-28 17:07 UTC, rldefa commented on docs/AboutUs.md
> +<img src="https://upload.wikimedia.org/wikipedia/en/b/b1/Portrait_placeholder.png" width="200px">
but why tho

2021-09-29 02:21 UTC, xianlinc commented on docs/AboutUs.md
> +<img src="https://upload.wikimedia.org/wikipedia/en/b/b1/Portrait_placeholder.png" width="200px">
Oh i see what you are referring to. In order for the grader to still pick it up, Gabriel may have to upload a placeholder image named his github username, if he wants to use a placeholder image. Not sure if url is allowed

2021-09-29 16:25 UTC, kawaiigabrielneko commented
I have made the required changes

2021-09-30 01:13 UTC, JoelChanZhiYang approved these changes
LGTM

2021-09-30 01:14 UTC, merged